server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ordering?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: '000822'
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.akijoey.entity